drop table jdbc.Employee;
drop schema jdbc restrict;

create schema jdbc;
create table jdbc.Employee (id bigint generated by default as identity (start with 1), firstName varchar(255), lastName varchar(255), dateOfBirth date, primary key (id));
